import {
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { v4 as uuidv4 } from 'uuid';
import { PrismaService } from '../database/prisma.service';
import { AlertSeed } from '../risk/risk.service';

@Injectable()
export class AlertsService {
  constructor(private readonly prisma: PrismaService) {}

  /** Bulk-create alerts generated by the risk evaluation. */
  async createMany(clientId: string, seeds: AlertSeed[]): Promise<void> {
    await this.prisma.alert.createMany({
      data: seeds.map((s) => ({
        id: uuidv4(),
        client_id: clientId,
        type: s.type,
        description: s.description,
      })),
    });
  }

  /**
   * List alerts, optionally filtered by resolution status.
   * @param resolved undefined = all | true = resolved only | false = pending only
   */
  async findAll(resolved?: boolean) {
    return this.prisma.alert.findMany({
      where: resolved !== undefined ? { is_resolved: resolved } : undefined,
      include: {
        client: {
          select: {
            id: true,
            full_name: true,
            identification: true,
            risk_level: true,
          },
        },
        resolver: {
          select: { id: true, name: true },
        },
      },
      orderBy: { created_at: 'desc' },
    });
  }

  /** Mark an alert as resolved. Only users with role "admin" are allowed. */
  async resolve(id: string, resolvedBy: string, userRole: string) {
    if (userRole !== 'admin') {
      throw new ForbiddenException(
        'Solo los administradores pueden resolver alertas',
      );
    }

    const alert = await this.prisma.alert.findUnique({ where: { id } });
    if (!alert) {
      throw new NotFoundException(`Alerta con ID "${id}" no encontrada`);
    }

    // Idempotent: resolving an already-resolved alert is a no-op
    if (alert.is_resolved) return alert;

    return this.prisma.alert.update({
      where: { id },
      data: {
        is_resolved: true,
        resolved_by: resolvedBy,
        resolved_at: new Date(),
      },
    });
  }
}
